import { Unbounded, Raleway } from 'next/font/google';
import './globals.css';

const unbounded = Unbounded({
    subsets: ['latin'],
    variable: '--font-unbounded',
});
const raleway = Raleway({ subsets: ['latin'], variable: '--font-raleway' });

export const metadata = {
    title: 'Profile Web',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body className={`${unbounded.variable} ${raleway.variable}`}>{children}</body>
        </html>
    );
}
